# The URL the site will be built for
base_url = "https://b.tinyops.ru"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_rss = true

theme = "tinyblog"

title = "TinyOps :: Блог"
description = "О технологиях, подходах и решении проблем простым языком"

taxonomies = [
 {name = "tags", rss = true},
 {name = "categories", paginate_by = 5, rss = true},  # 5 items per page for a term
 {name = "authors"} # Basic definition: no RSS or pagination
]

[extra]
# Put all your custom variables here
description = ""
website="tinyops.ru"
twitter=""
email = "eugene@tinyops.ru"

open_graph_url = "https://b.tinyops.ru"
open_graph_type = "blog"
open_graph_title = "Блог TinyOps"
open_graph_description = "О технологиях, подходах и решении проблем простым языком"
open_graph_image = ""

# Yandex.Metrika
yandex_webmaster_verification_code = "578eb2cc5cb8a301"

yandex_metrika_counter = "56992924"
