# The URL the site will be built for
base_url = "https://b.tinyops.ru"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true
feed_limit = 100

theme = "tinyblog"

title = "Блог TinyOps"
description = "О технологиях, подходах и решении проблем простым языком"

taxonomies = [
 {name = "tags", feed = true},
 {name = "categories", paginate_by = 10, feed = true},  # 5 items per page for a term
 {name = "authors"} # Basic definition: no RSS or pagination
]

[markdown]
highlight_code = true

[extra]
enable_about_blog_page = false

keywords = "блог про технологии, решение linux проблем, linux"

description = ""

website="tinyops.ru"
website_button_title = "Сайт"
website_button_hint = "Перейти на сайт"

twitter=""
twitter_button_title = "Twitter"
twitter_button_hint = "Перейти в Twitter"

email = "eugene@tinyops.ru"
email_button_title = "Написать на почту"
email_button_hint = "Написать на почту"

open_graph_url = "https://b.tinyops.ru"
open_graph_type = "blog"
open_graph_title = "Блог TinyOps"
open_graph_description = "О технологиях, подходах и решении проблем"
open_graph_image = ""

favicon_type = "image/vnd.microsoft.icon"

#----------------------------
# YANDEX
#----------------------------

# Yandex.Metrika
yandex_webmaster_verification_code = "578eb2cc5cb8a301"

yandex_metrika_counter = "56992924"

# Yandex Turbo Pages
# https://yandex.ru/dev/turbo/
yandex_turbo_pages = true
yandex_turbo_pages_metrika_id = 56992924
